import {worldRegions} from './regions';
import {useEffect,useRef,useState} from 'react';
import type {WorldSave} from './types';
import type {Attempt} from './challenges/types';
import {trainingPool,weakTopics} from './personalLearning';
import {recordAttempt} from './challenges/progress';
import {character,syncGrowth} from './growth';
import {accessConfig} from './access';
import {territories} from './catalog';
import Session from './challenges/Session';
import {emit} from './events';
export default function PersonalTraining({save,topic,region,mixed=false,immediate=false,demo=false,onSave,onBack,onTrain}:{save:WorldSave;topic?:string;region?:string;mixed?:boolean;immediate?:boolean;demo?:boolean;onSave:(s:WorldSave)=>void;onBack:()=>void;onTrain:(topic:string)=>void}) {
  const area=worldRegions(save).find(r=>r.id===region);
  const [pool,setPool]=useState(()=>trainingPool(save,topic,mixed,Math.random,area?.pool)),[index,setIndex]=useState(immediate?0:-1),[round,setRound]=useState(0);
  const session=useRef(crypto.randomUUID()),latest=useRef(save),correct=useRef(new Set<number>());
  latest.current=save;
  useEffect(()=>{const c=pool[index];if(c){emit("difficulty_assigned",{skill:c.skill,actual:c.difficultyTier,exercise:c.id,mixed,region});if(mixed)emit("misty_puzzle_started",{skill:c.skill,tier:c.difficultyTier});}},[index,round]);
  useEffect(()=>{if(immediate){emit("training_started",{topic,mixed,demo});if(mixed)emit('misty_run_started',{region});}},[]);
  const title=topic?territories.find(t=>t.id===topic)?.short:undefined;
  if(!pool.length)return <main className="activity-shell"><h1>Explore the tactics first</h1><p>Challenges from familiar topics will appear here.</p><button onClick={onBack}>Return to the map</button></main>;
  if(index<0)return <main className="activity-shell"><h1>{area?area.name:mixed?"The mist is clearing":title?"Practice: "+title:"Training hall"}</h1><p>{mixed?"Nobody tells you which tactic to use here. Find the idea yourself.":"Revisit the tactics in new positions. Your freed fortresses stay yours."}</p><p>{pool.length} puzzles per series · continue with another series</p>{save.learning&&Object.values(save.learning.adaptive?.topics||{}).some(t=>t.samples<3)&&<p>Your first answers help us choose the difficulty.</p>}<button className="world-button" onClick={()=>{emit('training_started',{topic,mixed});if(mixed)emit('misty_puzzle_started');setIndex(0);}}>Start practice →</button><button onClick={onBack}>← World map</button></main>;
  if(index>=pool.length){const weak=weakTopics(save)[0],name=territories.find(t=>t.id===weak)?.short;return <main className="activity-shell"><h1>Practice completed!</h1><p>Solved {correct.current.size} of {pool.length}</p>{mixed&&<p>Your record: {Math.max(correct.current.size,...(save.trainingSessions||[]).filter(r=>r.mixed).map(r=>r.correct))} solutions per series · difficulty reached {Math.max(...pool.map(c=>c.difficultyTier||1),...(save.trainingSessions||[]).filter(r=>r.mixed).map(r=>r.maxTier||1))} of 5</p>}<p>{correct.current.size>=4?"You are gaining practice at spotting chess tactics!":"Good practice. We will revisit these tactics later."}</p>{save.trainingSessions?.find(s=>s.id===session.current)?.reward===1&&<p>+1 hero development point</p>}{mixed&&weak&&<><p>{name}: this tactic was well hidden today. Practise it in the training ground?</p><button onClick={()=>onTrain(weak)}>Practise: {name}</button></>}{mixed&&<button className="world-button" onClick={()=>{session.current=crypto.randomUUID();correct.current=new Set();setPool(trainingPool(latest.current,topic,mixed,Math.random,area?.pool));setRound(round+1);setIndex(0);emit('misty_run_started',{round:round+2});}}>Next series →</button>}<button className="world-button" onClick={onBack}>To the map →</button></main>;}
  function next(){if(index+1===pool.length){const s=structuredClone(latest.current);s.trainingSessions ||= [];if(!s.trainingSessions.some(r=>r.id===session.current)){const today=new Date().toDateString();const earned=s.trainingSessions.filter(r=>new Date(r.at).toDateString()===today).reduce((n,r)=>n+r.reward,0);const reward=correct.current.size>=3&&earned<accessConfig.dailyTrainingPoints?1:0;if(reward)character(s).progress+=reward;if(demo)s.personalDemosCompleted=(s.personalDemosCompleted||0)+1;s.trainingSessions.push({id:session.current,at:Date.now(),topic,mixed,correct:correct.current.size,reward,region,maxTier:Math.max(...pool.map(c=>c.difficultyTier||1)),independent:(s.learning?.attempts||[]).filter(a=>pool.some(c=>c.id===a.challengeId)&&a.correct&&a.attempts===1&&!a.hintLevel).slice(-pool.length).length});onSave(syncGrowth(s));}emit('training_completed',{topic,mixed});if(mixed)emit('misty_run_ended',{round:round+1,correct:correct.current.size});}else {const fresh=trainingPool(latest.current,topic,mixed,Math.random,area?.pool)[0];if(fresh)setPool(old=>old.map((c,i)=>i===index+1?fresh:c));if(mixed)emit('misty_puzzle_started');}setIndex(index+1);}
  return <Session key={round+':'+index} exercise={pool[index]} mode={mixed?'mixed':'personal'} caption={(area?area.name:mixed?"Misty Lands":title?"Today’s practice: "+title:"Skill practice")+" · Puzzle "+(index+1)+" of "+pool.length} onExit={onBack} onResult={(a:Attempt)=>{if(a.correct)correct.current.add(index);const next=recordAttempt(latest.current,pool[index],{...a,mode:mixed?'mixed':'personal',pathSkill:undefined});latest.current=next;onSave(next);if(mixed)emit('misty_puzzle_solved',{correct:a.correct,skill:a.skill});}} onContinue={next}/>;
}
