import type {WorldSave} from './types';
import {skills,territories} from './catalog';
import {topicMastery} from './personalLearning';
export function ParentGate({onBack,onAdult}:{onBack:()=>void;onAdult:()=>void}){return <div className="journal-scrim"><section className="product-panel" role="dialog" aria-label="Ask a grown-up"><h1>Ask a grown-up</h1><p>Ask a parent to help open new practice activities.</p><button className="world-button" onClick={onAdult}>Ask a grown-up</button><button onClick={onBack}>Go back</button></section></div>;}
export function PremiumOffer({onClose,onOpen,training=false}:{onClose:()=>void;onOpen:()=>void;training?:boolean}){
 const title=training?"Open personal practice":"Open the whole world";
 return <div className="journal-scrim"><section className="product-panel" role="dialog" aria-label={title}><h1>{title}</h1><p>{training?"CHEZZIES notices which chess topics are trickier and suggests short challenges on those topics.":"For parents: more adventures and chess practice for your child."}</p><ul><li><strong>The game notices tricky topics</strong><br/>For example, repeated mistakes with pins lead to more pin practice.</li><li><strong>Revisits the topic</strong><br/>A similar idea will appear again in mixed challenges later.</li><li><strong>Shows progress to a parent</strong><br/>See what is going well and what to practise again.</li><li><strong>Opens the whole world</strong><br/>All fortresses, Misty Lands, the expanded training ground and new opponents.</li></ul><button className="world-button" onClick={onOpen}>Open full access</button><button onClick={onClose}>Not now</button></section></div>;
}
export function SavePrompt({arena,onSave,onSkip}:{arena:boolean;onSave:()=>void;onSkip:()=>void}){return <div className="journal-scrim"><section className="product-panel" role="dialog" aria-label="Save progress"><h1>{arena?"Save your results?":"Save your hero?"}</h1><p>Your adventure has begun. Create a free profile to save your hero, fortresses and games, and continue on another device.</p><button className="world-button" onClick={onSave}>Save progress</button><button onClick={onSkip}>Continue without an account</button><small>Progress will stay on this device.</small></section></div>;}
export function ParentProgress({save,onBack}:{save:WorldSave;onBack:()=>void}){const since=Date.now()-7*86400000,games=save.games.filter(g=>g.reason!=='in-progress'&&(g.finishedAt||0)>=since),rows=(save.learning?.attempts||[]).filter(a=>a.at>=since);return <div className="journal-scrim"><section className="product-panel"><h1>This week</h1><p>Puzzles solved: {new Set(rows.filter(a=>a.correct).map(a=>a.challengeId)).size}</p><p>Days played: {new Set([...rows.map(a=>new Date(a.at).toDateString()),...games.map(g=>new Date(g.finishedAt!).toDateString()) ]).size}</p><p>Games played: {games.length}</p><h2>Skills</h2>{skills.map(k=><p key={k}>{territories.find(t=>t.id===k)?.short}: {topicMastery(save,k).label}</p>)}<button onClick={onBack}>Go back</button></section></div>;}
