// Curated distinct positions; never a source for post-game reviews.
import type { Challenge } from "./types";
export const trainingChallenges: Challenge[] = [
  {
    id: "fork-1",
    skill: "fork",
    title: "Two targets, one knight",
    prompt: "Attack the king and rook with your knight.",
    fen: "2r1k3/8/8/8/4N3/8/8/6K1 w - - 0 1",
    solutions: ["e4d6"],
    explanation: "The knight on d6 gives check and attacks the rook on c8.",
    chapter: 1,
    kind: "move",
    concept: "Knight fork",
    difficulty: 1,
  },
  {
    id: "fork-2",
    skill: "fork",
    fen: "8/8/1B2pn1p/5pp1/4k3/2K5/8/8 b - - 0 1",
    solutions: ["f6d5"],
    title: "A fork among pieces",
    prompt: "Your knight is selected. Find a safe fork.",
    explanation: "The piece on d5 attacks the bishop on b6 and king on c3.",
    objective: "safeFork",
    difficulty: 1,
    chapter: 1,
    kind: "square",
    concept: "A fork in a game position",
  },
  {
    id: "fork-9",
    skill: "fork",
    fen: "8/8/8/3k1p2/1P2PP2/2BK1R2/8/8 b - - 0 1",
    solutions: ["f5e4"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on e4 attacks the rook on f3 and king on d3.",
    objective: "safeFork",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-10",
    skill: "fork",
    fen: "8/pp4p1/3k3r/5pN1/2KP1P2/8/8/8 w - - 0 1",
    solutions: ["g5f7"],
    title: "Guardian’s fork",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on f7 attacks the rook on h6 and king on d6.",
    objective: "safeFork",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-5",
    skill: "fork",
    fen: "8/N4k2/8/1Pnpp3/P7/2K1P3/1R6/8 b - - 0 1",
    solutions: ["c5a4"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on a4 attacks the rook on b2 and king on c3.",
    objective: "safeFork",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-4",
    skill: "fork",
    fen: "8/6k1/5N2/4Bn2/2Q5/3P4/4P1K1/5BR1 b - - 0 1",
    solutions: ["f5e3"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on e3 attacks the queen on c4, bishop on f1 and king on g2.",
    objective: "safeFork",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-3",
    skill: "fork",
    fen: "4k3/8/8/4p3/2P1P2n/1q1PK3/8/4B1N1 b - - 0 1",
    solutions: ["h4g2"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on g2 attacks the king on e3 and bishop on e1.",
    objective: "safeFork",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-11",
    skill: "fork",
    fen: "8/4k3/1np5/1p6/p2PPP2/P1P1K3/1B6/8 b - - 0 1",
    solutions: ["b6c4"],
    title: "Guardian’s fork",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on c4 attacks the king on e3 and bishop on b2.",
    objective: "safeFork",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-6",
    skill: "fork",
    fen: "8/8/4p2k/2p2p2/2P4P/1P1Pp3/8/2KR1N2 b - - 0 1",
    solutions: ["e3e2"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on e2 attacks the knight on f1 and rook on d1.",
    objective: "safeFork",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-12",
    skill: "fork",
    fen: "1nbr4/3p2k1/2q1ppNp/8/3P4/1K6/8/8 w - - 0 1",
    solutions: ["g6e7"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on e7 attacks the bishop on c8 and queen on c6.",
    objective: "safeFork",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-13",
    skill: "fork",
    fen: "1k4n1/6pp/4pp2/8/5KPQ/7P/5B1N/8 b - - 0 1",
    solutions: ["g7g5"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on g5 attacks the queen on h4 and king on f4.",
    objective: "safeFork",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-14",
    skill: "fork",
    fen: "2bk3r/3p3p/2pbp1p1/5pN1/3P4/8/3K1P2/8 w - - 0 1",
    solutions: ["g5f7"],
    title: "Guardian’s fork",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on f7 attacks the rook on h8, king on d8 and bishop on d6.",
    objective: "safeFork",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-7",
    skill: "fork",
    fen: "8/5k2/8/4P3/Pn3q2/4R1N1/3PK1P1/RNB2B2 b - - 0 1",
    solutions: ["b4c2"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on c2 attacks the rooks on e3 and a1.",
    objective: "safeFork",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-15",
    skill: "fork",
    fen: "8/8/5p1k/3pnP2/6rP/1RP1P2K/3B4/4Q2R b - - 0 1",
    solutions: ["e5f3"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on f3 attacks the queen on e1 and bishop on d2.",
    objective: "safeFork",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-8",
    skill: "fork",
    fen: "2b2r2/pp1p4/5P1p/1kp1P1p1/2N5/2B5/8/4K3 w - - 0 1",
    solutions: ["c4d6"],
    title: "A fork among pieces",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on d6 attacks the bishop on c8 and king on b5.",
    objective: "safeFork",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "fork-16",
    skill: "fork",
    fen: "8/3k4/4p1p1/2bp1p1p/2bp1P1P/5NP1/3B4/3KQ3 w - - 0 1",
    solutions: ["f3e5"],
    title: "Guardian’s fork",
    prompt: "Find a safe fork. Do not lose your attacking piece.",
    explanation: "The piece on e5 attacks the king on d7 and bishop on c4.",
    objective: "safeFork",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A fork in a game position",
  },
  {
    id: "mate-1",
    skill: "mate",
    title: "The last rank",
    prompt: "Give checkmate with your rook in one move.",
    fen: "7k/5K2/8/8/8/8/8/6R1 w - - 0 1",
    solutions: ["g1h1"],
    explanation: "The rook covers the h-file and your king covers g8 and g7.",
    chapter: 1,
    kind: "move",
    difficulty: 1,
  },
  {
    id: "mate-2",
    skill: "mate",
    fen: "8/8/3Q4/8/3Pk3/1KP5/P5P1/5B2 w - - 0 1",
    solutions: ["d6e5"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-3",
    skill: "mate",
    fen: "1r6/1P6/8/2p1p3/b1P4k/2KP4/5r2/8 b - - 0 1",
    solutions: ["f2c2"],
    title: "Guardian’s checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-4",
    skill: "mate",
    fen: "8/3Q4/8/5P2/1k6/1P1P4/P1R1KP2/3N4 w - - 0 1",
    solutions: ["d7a4"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-5",
    skill: "mate",
    fen: "4k2r/6Qp/3K1n2/3pp2P/8/5P2/8/8 w - - 0 1",
    solutions: ["g7e7"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-6",
    skill: "mate",
    fen: "8/8/8/2P1Bk2/3Q1N1P/3P4/1P2PK1P/5B2 w - - 0 1",
    solutions: ["f1h3"],
    title: "Guardian’s checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-7",
    skill: "mate",
    fen: "rnb1k3/8/1ppp4/p1q1p2p/K7/8/8/8 b - - 0 1",
    solutions: ["c5b4"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-8",
    skill: "mate",
    fen: "4B3/8/1b1kp3/3pRp2/3p1P2/8/2R5/3KQ3 w - - 0 1",
    solutions: ["e5e6"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-9",
    skill: "mate",
    fen: "4k3/8/1n1p1p2/1pp1p3/8/2P5/PP5P/K1B3q1 b - - 0 1",
    solutions: ["g1c1"],
    title: "Guardian’s checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-10",
    skill: "mate",
    fen: "5bn1/4k2p/1Q6/4p1pB/5q2/1PP5/5P2/3RK3 w - - 0 1",
    solutions: ["b6d6"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-11",
    skill: "mate",
    fen: "1k1r4/3bb3/1p1p1p2/p1pK4/6PQ/7P/2q5/8 b - - 0 1",
    solutions: ["c2d3"],
    title: "Find checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "mate-12",
    skill: "mate",
    fen: "rnb2b2/p1pp4/2k5/3p4/1P6/K2Q4/P1P4P/1q6 b - - 0 1",
    solutions: ["b1b4"],
    title: "Guardian’s checkmate",
    prompt: "Find checkmate in one move. Check every escape route.",
    explanation:
      "Check! The king cannot escape, block or capture the attacker.",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "Checkmate among pieces",
  },
  {
    id: "defense-2",
    skill: "defense",
    title: "Remove the threat",
    prompt: "The rook gives check. Capture it with your bishop.",
    fen: "7k/8/8/8/4r3/8/2B5/4K3 w - - 0 1",
    solutions: ["c2e4"],
    explanation: "Sometimes the best defense is to capture the attacker.",
    chapter: 1,
    kind: "move",
    difficulty: 1,
  },
  {
    id: "defense-1",
    skill: "defense",
    fen: "8/8/6Q1/5p2/6k1/4P3/6PP/3K3R b - - 0 1",
    solutions: ["g4h4"],
    title: "Save a piece",
    prompt: "The king is in check. Find the only escape.",
    explanation: "The king moved to its only safe square.",
    objective: "onlyEscape",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-3",
    skill: "defense",
    fen: "3B4/pp6/2b5/1kp5/2P5/PP6/3K4/8 b - - 0 1",
    solutions: ["b5a6"],
    title: "Guardian’s defense",
    prompt: "The king is in check. Find the only escape.",
    explanation: "The king moved to its only safe square.",
    objective: "onlyEscape",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-4",
    skill: "defense",
    fen: "8/8/2k5/p7/PbP5/1P1B4/2K5/R5q1 b - - 0 1",
    solutions: ["g1a1"],
    title: "Save a piece",
    prompt: "The piece on g1 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on a1. The threat is gone.",
    objective: "rescue",
    rescueSquare: "g1",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-5",
    skill: "defense",
    fen: "r6Q/p2k4/1pp5/1b6/1P6/8/PK6/8 w - - 0 1",
    solutions: ["h8a8"],
    title: "Save a piece",
    prompt: "The piece on h8 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on a8. The threat is gone.",
    objective: "rescue",
    rescueSquare: "h8",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-6",
    skill: "defense",
    fen: "8/N4k2/4pn2/1Pbp4/P2P4/3BP3/3K4/8 w - - 0 1",
    solutions: ["d4c5"],
    title: "Guardian’s defense",
    prompt: "The piece on a7 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on c5. The threat is gone.",
    objective: "rescue",
    rescueSquare: "a7",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-7",
    skill: "defense",
    fen: "4k3/p7/1n6/1pp5/8/2Pq4/PP6/1KB3N1 w - - 0 1",
    solutions: ["b1a1"],
    title: "Save a piece",
    prompt: "The king is in check. Find the only escape.",
    explanation: "The king moved to its only safe square.",
    objective: "onlyEscape",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-8",
    skill: "defense",
    fen: "4k3/8/1pp5/4p3/1PP1P3/q1KP4/3BN3/8 w - - 0 1",
    solutions: ["c3c2"],
    title: "Save a piece",
    prompt: "The king is in check. Find the only escape.",
    explanation: "The king moved to its only safe square.",
    objective: "onlyEscape",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-9",
    skill: "defense",
    fen: "Q6r/5kpp/4pn2/5p1P/5P1R/4q1PK/8/8 w - - 0 1",
    solutions: ["a8h8"],
    title: "Guardian’s defense",
    prompt: "The piece on a8 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on h8. The threat is gone.",
    objective: "rescue",
    rescueSquare: "a8",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-10",
    skill: "defense",
    fen: "2r5/5pb1/2ppkB2/4p2p/4P1b1/8/6P1/4K1N1 w - - 0 1",
    solutions: ["f6g7"],
    title: "Save a piece",
    prompt: "The piece on f6 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on g7. The threat is gone.",
    objective: "rescue",
    rescueSquare: "f6",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-11",
    skill: "defense",
    fen: "8/8/5kp1/3b1p2/5K1P/4P1P1/1P1P1PB1/2B4R b - - 0 1",
    solutions: ["d5g2"],
    title: "Save a piece",
    prompt: "The piece on d5 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on g2. The threat is gone.",
    objective: "rescue",
    rescueSquare: "d5",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "defense-12",
    skill: "defense",
    fen: "4k3/p7/1p6/1Pp5/K1PB4/3P4/P5P1/bN2NB1R w - - 0 1",
    solutions: ["d4a1"],
    title: "Guardian’s defense",
    prompt: "The piece on d4 is attacked. Save it by capturing the attacker.",
    explanation: "You removed the attacker on a1. The threat is gone.",
    objective: "rescue",
    rescueSquare: "d4",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "Defense in a game",
  },
  {
    id: "pin-1",
    skill: "pin",
    title: "Pin the knight",
    prompt: "Place the bishop so the knight cannot move away from its king.",
    fen: "4k3/3n4/8/8/8/8/8/5BK1 w - - 0 1",
    solutions: ["f1b5"],
    explanation:
      "Bishop b5, knight d7 and king e8 share a diagonal. The knight is pinned.",
    chapter: 1,
    kind: "move",
    difficulty: 1,
  },
  {
    id: "pin-2",
    skill: "pin",
    fen: "8/1k6/3K4/PP1P1p2/5r2/7p/8/8 b - - 0 1",
    solutions: ["f4d4"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-3",
    skill: "pin",
    fen: "8/7r/4Rb2/1p3p2/5k1p/7P/3K2P1/8 w - - 0 1",
    solutions: ["e6f6"],
    title: "Guardian’s pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-4",
    skill: "pin",
    fen: "3k4/2r5/2p2p2/2P4p/4Pp2/5P2/8/4K3 b - - 0 1",
    solutions: ["c7e7"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-5",
    skill: "pin",
    fen: "r5n1/1ppb3p/1k6/5p2/8/4P3/8/4K3 b - - 0 1",
    solutions: ["a8e8"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-6",
    skill: "pin",
    fen: "8/2pQ4/8/3p1p1k/8/1PPPP3/3NP3/3K4 w - - 0 1",
    solutions: ["d7d5"],
    title: "Guardian’s pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-7",
    skill: "pin",
    fen: "8/pk6/6p1/PP1PKp2/1r6/7p/7P/8 b - - 0 1",
    solutions: ["b4b5"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-8",
    skill: "pin",
    fen: "3R4/2r2k2/p1p2p2/7p/2P1Pp2/5P2/4K3/8 b - - 0 1",
    solutions: ["c7e7"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-9",
    skill: "pin",
    fen: "2R5/1r6/3pnb2/pp3p2/4kP1p/4P3/2K3P1/8 w - - 0 1",
    solutions: ["c8e8"],
    title: "Guardian’s pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-10",
    skill: "pin",
    fen: "5r2/pp2k1p1/5r2/PP2Np2/3P1P2/4K3/3N4/8 b - - 0 1",
    solutions: ["f6e6"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-11",
    skill: "pin",
    fen: "4n3/1k1rbb2/pp1p4/5p2/2P5/P3PP2/2K5/8 b - - 0 1",
    solutions: ["d7c7"],
    title: "A hidden pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "pin-12",
    skill: "pin",
    fen: "8/4b3/3p1pk1/4p1qp/PPP1P3/2N2P2/5K2/3RN3 b - - 0 1",
    solutions: ["g5f4"],
    title: "Guardian’s pin",
    prompt: "Create a new pin to the king. Choose a safe move.",
    explanation:
      "The king is behind the pinned piece. It cannot leave the line and expose check.",
    objective: "newPin",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A pin in a game",
  },
  {
    id: "double-1",
    skill: "doubleAttack",
    title: "Check and a tower",
    prompt: "Give check and attack the rook at the same time.",
    fen: "r5k1/8/8/8/8/8/8/3Q2K1 w - - 0 1",
    solutions: ["d1d5"],
    explanation:
      "The queen on d5 gives check along the g8 diagonal and attacks rook a8 along the other diagonal.",
    chapter: 1,
    kind: "move",
    difficulty: 1,
  },
  {
    id: "double-2",
    skill: "doubleAttack",
    fen: "8/1p6/2k1b3/2P5/5P2/2B1K3/3R4/8 w - - 0 1",
    solutions: ["d2d6"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on d6 attacks the bishop on e6 and king on c6.",
    objective: "safeDouble",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-3",
    skill: "doubleAttack",
    fen: "8/1p6/4k3/PP2Np2/2NP1P2/8/4K3/8 b - - 0 1",
    solutions: ["e6d5"],
    title: "Guardian’s double attack",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on d5 attacks the knights on c4 and e5.",
    objective: "safeDouble",
    difficulty: 1,
    chapter: 1,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-4",
    skill: "doubleAttack",
    fen: "8/8/6k1/6q1/1PP1P3/2NR1P2/5K2/4N3 b - - 0 1",
    solutions: ["g5c1"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on c1 attacks the knights on e1 and c3.",
    objective: "safeDouble",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-5",
    skill: "doubleAttack",
    fen: "8/2pbr1pp/8/3p1pk1/1Q6/8/8/3K4 w - - 0 1",
    solutions: ["b4e7"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on e7 attacks the king on g5 and bishop on d7.",
    objective: "safeDouble",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-6",
    skill: "doubleAttack",
    fen: "N3qk2/4p3/p1pp4/8/1BPP4/8/1P6/4K3 b - - 0 1",
    solutions: ["e8b8"],
    title: "Guardian’s double attack",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on b8 attacks the knight on a8 and bishop on b4.",
    objective: "safeDouble",
    difficulty: 2,
    chapter: 2,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-7",
    skill: "doubleAttack",
    fen: "8/pp2B2p/1kb5/5p2/2P4r/4PP2/3K4/8 w - - 0 1",
    solutions: ["e7d8"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on d8 attacks the rook on h4 and king on b6.",
    objective: "safeDouble",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-8",
    skill: "doubleAttack",
    fen: "r1b3nB/ppp1n3/4k3/5p2/8/3R4/8/4K3 w - - 0 1",
    solutions: ["d3d8"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on d8 attacks the knight on g8 and bishop on c8.",
    objective: "safeDouble",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-9",
    skill: "doubleAttack",
    fen: "8/6k1/3p4/3Bp1q1/1PP1P3/P1NN1P2/5K2/R7 b - - 0 1",
    solutions: ["g5d2"],
    title: "Guardian’s double attack",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on d2 attacks the knight on c3, king on f2 and knight on d3.",
    objective: "safeDouble",
    difficulty: 3,
    chapter: 3,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-10",
    skill: "doubleAttack",
    fen: "1nk5/8/4b3/p2p2Q1/3P1P1P/2PBP1P1/8/2K5 w - - 0 1",
    solutions: ["g5e5"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on e5 attacks the knight on b8 and bishop on e6.",
    objective: "safeDouble",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-11",
    skill: "doubleAttack",
    fen: "8/1pp1r3/4k3/Q2p4/7b/1PPPP3/3N4/2RK4 w - - 0 1",
    solutions: ["a5b4"],
    title: "Two threats",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on b4 attacks the rook on e7 and bishop on h4.",
    objective: "safeDouble",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A double attack in a game",
  },
  {
    id: "double-12",
    skill: "doubleAttack",
    fen: "r7/ppp5/3k4/n2p4/8/1PPPP3/1Q1NP3/2RK4 w - - 0 1",
    solutions: ["b2a3"],
    title: "Guardian’s double attack",
    prompt: "Create two threats in one move. Check your opponent’s reply.",
    explanation: "The piece on a3 attacks the king on d6 and knight on a5.",
    objective: "safeDouble",
    difficulty: 4,
    chapter: 4,
    kind: "move",
    concept: "A double attack in a game",
  },
];
