import {useEffect,useRef,useState} from 'react';
import type {WorldSave} from '../types';
import HeroActor from '../HeroActor';
import {character} from '../growth';
import {weaponTier} from '../weapons';
import {heroConfig,heroProgression,energyRules} from '../heroConfig';
import {canAccess,accessConfig} from '../access';
import {emit} from '../events';
import {playWorldSound} from '../worldSound';
import {saveRangeRun} from './progress';
import {EnergyRound,type EnergyTarget,type AimPoint} from './energyModel';
import Polygon from './Polygon';
import './energy.css';
type Props={save:WorldSave;onSave:(s:WorldSave)=>void;onMap:()=>void;onChess:()=>void;onOfficer:()=>void;onLobby?:()=>void};
export default function HeroPolygon(props:Props){return (props.save.player.selectedCharacter||'inventor')==='knight'?<Polygon {...props}/>:<EnergyPolygon key={props.save.player.selectedCharacter} {...props}/>;}
function TargetArt({kind}:{kind:EnergyTarget['kind']}){return <svg viewBox="0 0 80 96" aria-hidden="true"><ellipse cx="40" cy="90" rx="27" ry="5" fill="#061e2d88"/><path d="M34 56h12v28l15 4H19l15-4Z" fill="#71858c" stroke="#bec9bf" strokeWidth="3"/>{kind==='crystal'?<><path d="M40 5 62 31 55 61 40 74 25 61 18 31Z" fill="#387ba8" stroke="#a7edff" strokeWidth="4"/><path d="m40 5-8 33 8 36 8-36Z" fill="#c5f8ff"/><path d="m18 31 22 7 22-7" fill="none" stroke="#d8fdff" strokeWidth="3"/></>:kind==='tower'?<><path d="M14 12h12v12h8V12h12v12h8V12h12v25l-8 5v33H22V42l-8-5Z" fill="#829599" stroke="#e6d6a6" strokeWidth="4"/><path d="M32 74V51q8-12 16 0v23" fill="#1b3c50"/><path d="M22 39h36M23 46h13m11-1h10" stroke="#384f60" strokeWidth="3"/></>:<><path d="M11 11 40 4 69 11v31q0 24-29 36Q11 66 11 42Z" fill="#806344" stroke="#edcb7e" strokeWidth="5"/><path d="M27 8v62m26-62v62" stroke="#bd9062" strokeWidth="4"/><circle cx="40" cy="37" r="17" fill="#204e62" stroke="#efd99c" strokeWidth="4"/><circle cx="40" cy="37" r="6" fill="#f1cd79"/></>}</svg>;}
function Guide({hero,onClose}:{hero:string;onClose:()=>void}){return <div className="journal-scrim"><section className="energy-guide product-panel" role="dialog" aria-label="How to play in the training ground"><h2>{hero==='mage'?"Choose the chain’s first target":"Aim → hold → release!"}</h2><div className={'ghost-demo ghost-'+hero} aria-hidden="true"><i className="ghost-object first"/><i className="ghost-object second"/><i className="ghost-ray"/><i className="ghost-hand">☝</i></div><p>{hero==='mage'?"Tap a target. With an improved sceptre, lightning jumps to its neighbours!":"Hold, move your aim and release. More charge makes a stronger beam."}</p><button className="world-button" onClick={onClose}>Got it, let’s play!</button></section></div>;}
function EnergyPolygon({save,onSave,onMap,onLobby}:Props){
 const hero=save.player.selectedCharacter||'inventor',parts=character(save,hero).equippedParts.length,owned=weaponTier(parts);
 const [tier]=useState(()=>(canAccess('polygon',owned)||(save.miniGames?.pendingWeaponTest?.hero===hero&&save.miniGames.pendingWeaponTest.level===owned))?owned:accessConfig.freePolygonLevel);
 const config=heroConfig[hero],rules=energyRules(hero,tier),[screen,setScreen]=useState<'intro'|'play'|'result'>('intro'),[paused,setPaused]=useState(false),[guide,setGuide]=useState(false),[,render]=useState(0);
 const model=useRef(new EnergyRound(hero,tier)),stage=useRef<HTMLDivElement>(null),saved=useRef(false),saveRef=useRef(save),session=useRef(''),origins=useRef<AimPoint[]>([]),lastShot=useRef(-10),trial=useRef(save.miniGames?.pendingWeaponTest?.hero===hero);
 saveRef.current=save;const m=model.current;
 function finish(completed:boolean){if(saved.current)return;saved.current=true;const run=m.result(session.current,completed);onSave(saveRangeRun(saveRef.current,run));emit('mini_game_finished',{game:config.trainingGameType,...run});setScreen('result');}
 useEffect(()=>{if(screen!=='play'||paused||guide)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;if(document.hidden){m.cancel();return;}const box=stage.current?.getBoundingClientRect();if(box){m.setViewport(box.width,box.height);origins.current=[...stage.current!.querySelectorAll('.weapon-anchor')].map(el=>{const r=el.getBoundingClientRect();return {x:(r.left+r.width/2-box.left)/box.width*100,y:(r.top+r.height/2-box.top)/box.height*100};});}m.step(dt);if(m.shotAt!==lastShot.current){lastShot.current=m.shotAt;playWorldSound(hero==='mage'?'lightningFire':'laserFire');if(m.gain)playWorldSound(m.flash.length>1?'multiHit':'success');}render(n=>n+1);if(m.time>=heroProgression.roundSeconds)finish(true);},32);return()=>clearInterval(timer);},[screen,paused,guide]);
 function start(){model.current=new EnergyRound(hero,tier);session.current=crypto.randomUUID();saved.current=false;lastShot.current=-10;setPaused(false);setScreen('play');setGuide(!saveRef.current.miniGames?.guideSeen?.[hero]);emit('mini_game_opened',{game:config.trainingGameType,hero,weaponLevel:tier});}
 function closeGuide(){const s=structuredClone(saveRef.current);s.miniGames||={};s.miniGames.guideSeen||={};s.miniGames.guideSeen[hero]=true;onSave(s);setGuide(false);}
 function point(x:number,y:number){const r=stage.current!.getBoundingClientRect();return {x:(x-r.left)/r.width*100,y:(y-r.top)/r.height*100};}
 const instruction=hero==='mage'?(tier===1?"Tap a target to strike with the sceptre.":"Choose the first target. Catch the moment when targets are close together!"):"Hold to charge. Aim and release!";
 const best=save.miniGames?.polygon?.[hero]?.byWeapon[tier]||0;
 if(screen!=='play')return <main className="energy-lobby activity-shell" data-game-type={config.trainingGameType}><div><span>HERO TRAINING GROUND · {tier} / {config.upgrades.length}</span><h1>{screen==='result'?"Great practice!":config.upgrades[tier-1]}</h1>{screen==='result'?<><p>Record: {best.toLocaleString('ru')}</p><p>Hits: {m.targetsHit}</p><p>Best streak: x{hero==='mage'?m.bestMultiHit:m.bestCombo}</p>{trial.current&&<p>{config.upgrades[tier-1]} works! {config.effects[tier-1]}.</p>}</>:<><p>{instruction}</p><p>{config.effects[tier-1]}</p><p>Set your record in 60 seconds.</p></>}{owned>tier&&<p>Basic mode. Your improvements are saved.</p>}<button className="world-button" onClick={start}>{screen==='result'?"Again":"Start · 60 seconds"}</button><button className="lesson-secondary" onClick={onLobby||onMap}>Return to the training ground</button></div><div className="energy-lobby-actor"><HeroActor id={hero} parts={parts} celebrating={screen==='result'}/></div></main>;
 const bolt=(a:AimPoint,b:AimPoint)=>Array.from({length:15},(_,i)=>{const t=i/14;return (a.x+(b.x-a.x)*t)+','+(a.y+(b.y-a.y)*t+(i&&i<14?Math.sin(i*8)*1.4:0));}).join(' ');
 const rays=m.flash.length?m.flash:[{...m.aim,id:-1}],elapsed=m.time-m.shotAt;
 return <main className={'energy-game energy-'+hero} data-game-type={config.trainingGameType} data-weapon-level={tier}><header><button onClick={()=>{m.cancel();setPaused(true);}}>Pause</button><strong>{Math.ceil(heroProgression.roundSeconds-m.time)} sec · {m.score} points</strong><button aria-label="How to play" onClick={()=>{m.cancel();setGuide(true);}}>?</button></header><p>{instruction}</p><div className="energy-stage" ref={stage} data-wave={m.wave} data-shots={m.shots} data-hits={m.targetsHit} data-origin={config.attackOrigin} tabIndex={hero==='inventor'?0:-1} aria-label={hero==='inventor'?"Aim: hold, point and release":"Ladiator’s targets"}
 onPointerDown={e=>{if(hero!=='inventor'||paused||guide)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.focus();m.hold(point(e.clientX,e.clientY));playWorldSound('laserCharge');render(n=>n+1);}}
 onPointerMove={e=>{if(hero==='inventor'&&!paused&&!guide){m.setAim(point(e.clientX,e.clientY));render(n=>n+1);}}}
 onPointerUp={e=>{if(hero==='inventor'&&!paused&&!guide){m.release(point(e.clientX,e.clientY));render(n=>n+1);}}} onPointerCancel={()=>m.cancel()}
 onKeyDown={e=>{if(hero!=='inventor'||paused||guide)return;if(e.key===' '||e.key==='Enter'){e.preventDefault();if(!e.repeat)m.hold(m.aim);}else if(e.key.startsWith('Arrow')){e.preventDefault();m.setAim({x:m.aim.x+(e.key==='ArrowRight'?3:e.key==='ArrowLeft'?-3:0),y:m.aim.y+(e.key==='ArrowDown'?3:e.key==='ArrowUp'?-3:0)});render(n=>n+1);}}} onKeyUp={e=>{if(hero==='inventor'&&(e.key===' '||e.key==='Enter'))m.release();}}>
 <div className="energy-actor"><HeroActor id={hero} parts={parts} attacking={m.charging||m.firing}/></div>
 {hero==='mage'&&rules.chainCount>1&&<svg className="energy-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{m.targets.filter(t=>t.hitAt===undefined).flatMap((a,i,all)=>all.slice(i+1).filter(b=>Math.hypot(a.x-b.x,a.y-b.y)<=rules.reach).map(b=><line key={a.id+'-'+b.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>))}</svg>}
 {m.targets.map((t,i)=><button key={t.id} className={'energy-target physical-target '+(t.hitAt!==undefined?'target-hit':'')} data-target-id={t.id} data-x={t.x} data-y={t.y} data-kind={t.kind} style={{left:t.x+'%',top:t.y+'%'}} aria-label={"Target "+(i+1)} tabIndex={hero==='mage'?0:-1} disabled={paused||guide||t.hitAt!==undefined} onClick={()=>{if(hero==='mage'&&!paused&&!guide){m.fire(t.id);playWorldSound('lightningCharge');render(n=>n+1);}}}><TargetArt kind={t.kind}/>{t.hitAt!==undefined&&<><i className="impact-burn"/><i className="impact-sparks"/></>}</button>)}
 {hero==='inventor'&&<div className={'energy-reticle '+(m.held!==null?'reticle-charging':'')} style={{left:m.aim.x+'%',top:m.aim.y+'%',background:'conic-gradient(#ffd46b '+m.charge*360+'deg, transparent 0deg)'}} aria-hidden="true"><i/><b/></div>}
 <svg className="energy-effects" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{m.charging&&origins.current.map((o,i)=><circle key={i} cx={o.x} cy={o.y} r={1+(hero==='mage'?1:m.charge*2)} fill={hero==='mage'?'#9af5ff':'#ffe08a'}/>)}{m.firing&&rays.map((target,i)=>{if(hero==='mage'&&elapsed<i*.09)return null;const from=i===0?origins.current[0]:hero==='mage'?m.flash[i-1]:origins.current[Math.min(i,origins.current.length-1)];if(!from)return null;return <g key={target.id} data-ray-origin={i===0?config.attackOrigin:hero==='mage'?'target':config.attackOrigin}>{hero==='mage'?<polyline points={bolt(from,target)} stroke="#bdfbff" strokeWidth={.5+tier*.12} fill="none"/>:<line x1={from.x} y1={from.y} x2={target.x} y2={target.y} stroke="#fff1b9" strokeWidth={.3+m.shotCharge*.7}/>}</g>;})}</svg>
 {m.feedback&&<div className={'energy-feedback '+(m.gain?'feedback-hit':'feedback-miss')} key={m.shotAt} role="status"><strong>{m.feedback}</strong>{m.gain>0&&<span>+{m.gain}</span>}</div>}
 </div>{hero==='inventor'&&<div className="energy-charge"><strong>CHARGE: {m.charge<.35?"low":m.charge<.8?"good":"maximum"}</strong><div className="energy-meter"><i style={{left:0,width:m.charge*100+'%'}}/></div><div className="charge-labels"><span>Low</span><span>Good</span><span>Maximum</span></div></div>}{guide&&<Guide hero={hero} onClose={closeGuide}/>} {paused&&!guide&&<div className="journal-scrim"><section className="product-panel"><h1>Pause</h1><button className="world-button" onClick={()=>setPaused(false)}>Continue</button><button onClick={()=>finish(false)}>End the round</button></section></div>}</main>;
}
