export const origin='https://chezzies.app';
export const description='CHEZZIES is an online chess adventure game for kids. Explore a fantasy world and practice chess through interactive challenges, free in your browser.';
export const pages=[
{slug:'chess-games-for-kids',title:'Chess Games for Kids — A Free Adventure | CHEZZIES',h1:'A chess game with a world to explore',intro:'CHEZZIES is a free chess adventure game for kids. Choose a hero, explore castles and solve short chess challenges in your browser.',sections:[
['What makes this a chess adventure?','Your hero travels across a fantasy map. Inside each fortress, chess challenges lead through stages to a final guardian. Completing challenges develops your hero and opens the next part of the journey.'],
['What can children play?','Children can solve tactic challenges, play full games against computer opponents in the Arena, or try their hero’s abilities in the training ground. The adventure brings them back to real chess positions.'],
['What is a good chess game for a beginner?','Look for understandable goals, legal moves and feedback that explains the position. A short challenge can be easier to approach than an entire game. In CHEZZIES, children can explore the piece guide and practise one idea at a time.'],
['Is CHEZZIES free?','Yes. The international version is free to play. There are no subscriptions or paid content limits. Some locations open through gameplay progress.']
],links:['online-chess-for-kids','chess-puzzles-for-kids']},
{slug:'online-chess-for-kids',title:'Online Chess for Kids — Play in Your Browser | CHEZZIES',h1:'An online chess adventure for kids',intro:'Kids can play CHEZZIES online in a web browser. Start a free adventure, practise chess challenges and meet computer opponents in the Arena.',sections:[
['How do children start playing?','Select Start Adventure, choose a hero and tell the game how familiar you are with chess. Explore the map or open the piece guide. You do not need an account or a payment to begin.'],
['Who do children play against?','The Arena uses computer-controlled opponents with different difficulty levels. This version does not provide live multiplayer matchmaking or a player chat.'],
['Where is progress saved?','Guest progress is saved in the current browser. A free CHEZZIES international account can save adventure progress on the server. International accounts are separate from chezzies.ru. Clearing browser data can remove unsaved guest progress.'],
['Does it work on a phone?','CHEZZIES runs in a browser on phones, tablets and desktop computers. The game adapts its navigation and board to the screen. A larger screen can help when first learning to recognise pieces.']
],links:['chess-games-for-kids','parents']},
{slug:'learn-chess-for-kids',title:'Learn Chess for Kids Through Play | CHEZZIES',h1:'Learn chess through small discoveries',intro:'CHEZZIES helps young chess beginners practise checkmate, forks, pins, double attacks and defense through interactive positions in a fantasy adventure.',sections:[
['How can kids begin learning chess?','Start by exploring how each piece moves. Then try a small position with a clear goal, such as escaping check or finding an attack. Ask the child to explain what changed after the move.'],
['How does CHEZZIES teach chess?','The piece guide demonstrates movement. Fortress challenges focus on individual tactical ideas, with hints and feedback. Full Arena games let children use those ideas in longer positions.'],
['What should beginners practise first?','Learn legal piece movement and how to keep the king safe. Then explore checkmate, undefended pieces and simple double threats. Revisit an idea in several positions rather than memorising a single move.'],
['How can a parent follow along?','Open the progress view to see recorded challenges, games and skill practice in this browser. Talk about a move together. Progress records describe activity in the game; they do not certify learning outcomes.']
],links:['how-to-play-chess-for-kids','chess-puzzles-for-kids']},
{slug:'how-to-play-chess-for-kids',title:'How to Play Chess for Kids — Beginner Guide | CHEZZIES',h1:'How to play chess: a first guide for kids',intro:'Chess is a game for two sides. Players take turns moving one piece. The goal is checkmate: attacking the other king so it has no legal way to escape.',sections:[
['How do you set up a chessboard?','Place the board with a light square at each player’s bottom-right corner. Put rooks in the corners, then knights and bishops. The queen starts on her own colour; the king takes the remaining square. Pawns fill the row in front. White moves first.'],
['How do the pieces move?','Rooks move straight along ranks and files. Bishops move diagonally. Queens combine rook and bishop movement. Knights move two squares in one direction and one across, and can jump over pieces. Kings move one square in any direction, but never into attack.'],
['What about pawns?','Pawns move one square forward and capture one square diagonally forward. From their starting square, they may advance two squares if both squares are empty. A pawn that reaches the far end becomes a queen, rook, bishop or knight.'],
['What is check, and what is checkmate?','Check means the king is under attack. You must escape by moving the king, capturing the attacker or blocking the attack when possible. If none of those is legal, it is checkmate. The king is never captured.'],
['Can a game end without checkmate?','Yes. If a player has no legal move and is not in check, the game is a draw by stalemate. Games can also be drawn by repetition or other rules.'],
['Are there special moves?','Castling moves a king two squares towards its rook and brings that rook to the square the king crossed. Neither may have moved; the path must be clear, and the king cannot castle out of, through or into check. En passant lets a pawn capture an opposing pawn immediately after it advances two squares to stand beside it, as if it had moved only one.'],
['What should I try next?','Explore the piece guide in CHEZZIES, then try a short challenge. The board checks legal moves while you practise. Take your time and look at what the other side is threatening.']
],links:['learn-chess-for-kids','chess-puzzles-for-kids']},
{slug:'chess-puzzles-for-kids',title:'Chess Puzzles for Kids — Five Tactics to Explore | CHEZZIES',h1:'Small chess puzzles. Big discoveries.',intro:'Chess puzzles give kids a position and a specific challenge. In CHEZZIES, children practise five tactical ideas: checkmate, forks, pins, double attacks and defense.',sections:[
['What is checkmate?','Checkmate is a check with no legal escape. Try looking for a move that attacks the king while covering its escape squares.'],
['What is a chess fork?','A fork is one piece attacking two or more enemy pieces at once. A knight can fork a king and a rook, forcing a response to check while leaving the rook under attack.'],
['What is a pin?','A pin restricts a piece because moving it would expose a piece behind it. If the piece behind is its king, moving out of that line is illegal. A pin against a queen can be costly to break, but is not automatically illegal.'],
['What is a double attack?','A double attack creates two threats with one move. A fork is one type; another is moving a piece to create a threat while uncovering an attack from a different piece.'],
['How do you practise defense?','First identify the threat. You might move the attacked piece, capture the attacker, block a line or add protection. If your king is in check, your move must remove the check.'],
['Are chess puzzles useful for beginners?','A focused position lets a beginner examine one idea without managing a whole game. Use hints when needed, then explain why the move works. CHEZZIES combines these positions with opportunities to play full games.']
],links:['learn-chess-for-kids','how-to-play-chess-for-kids']},
{slug:'parents',title:'CHEZZIES for Parents — Free Chess Through Play',h1:'They come to play. They discover chess.',intro:'CHEZZIES is a free browser-based chess adventure for young beginners. Children choose a hero, solve chess challenges, explore a fantasy map and play against computer opponents.',sections:[
['Who is CHEZZIES for?','CHEZZIES is designed for young chess beginners. There is no verified numerical age range for this release. A child who is still learning to read may enjoy playing with an adult alongside them.'],
['What will my child do?','Children practise checkmate, forks, pins, double attacks and defense. They progress through fortress stages, develop their chosen hero and can play longer games in the Arena. The training ground offers a short arcade activity with the same heroes.'],
['Is everything free?','Yes. The international version has no payment requirement, subscriptions or paid limits. Locked locations reflect adventure progress or content not yet available, not a purchase requirement.'],
['Can I see progress?','The in-game progress summary shows recorded activity and skill practice. Guest progress stays in this browser; an international account saves adventure progress separately on the server. International and chezzies.ru accounts are separate.'],
['Are there other players or chat?','The Arena opponents are computer-controlled. This international release has no player chat or multiplayer matchmaking. It does not offer parental time controls or a separate parent account.'],
['What data does this version use?','The browser stores game progress and a limited local activity log. The activity interface accepts event names and broad traffic categories, without names, emails or full referring URLs. No external analytics collector is enabled in this release.'],
['How can I help my child?','Try a challenge together and ask what each piece attacks. Let the child make a move, inspect the feedback and try again. Stop when the child wants a break; there is no required daily schedule.']
],links:['learn-chess-for-kids','online-chess-for-kids']}
];
