import {mkdirSync,writeFileSync} from 'node:fs';
import {pages,origin,description} from './content.mjs';
import {homepage} from './homepage.mjs';
const esc=s=>s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export const cta=(label='START ADVENTURE')=>`<a class="cta" href="/play/">${label}<span aria-hidden="true">↗</span></a>`;
const header=`<header class="site-header"><a class="logo" href="/" aria-label="CHEZZIES home"><span aria-hidden="true">♜</span> CHEZZIES</a><nav aria-label="Main navigation"><a href="/play/">Play</a><a href="/#world">World</a><a href="/parents/">Parents</a><a href="/#about">About</a></nav>${cta()}</header>`;
const footer=`<footer><a class="logo" href="/">CHEZZIES</a><p>A little courage. A clever move. A whole new world.</p><nav aria-label="Explore CHEZZIES">${pages.map(p=>`<a href="/${p.slug}/">${p.slug==='parents'?'For parents':p.slug.replaceAll('-',' ')}</a>`).join('')}</nav><small>© ${new Date().getFullYear()} CHEZZIES · Free to play in your browser.</small></footer>`;
function html({title,h1,body,slug='',intro=description,game=false,noindex=false}){const url=origin+'/'+(slug?slug+'/':'');const entities=[{'@type':'Organization','@id':origin+'/#organization',name:'CHEZZIES',url:origin+'/'},{'@type':'WebSite','@id':origin+'/#website',name:'CHEZZIES',url:origin+'/',description,publisher:{'@id':origin+'/#organization'}},{'@type':'SoftwareApplication','@id':origin+'/#game',name:'CHEZZIES',url:origin+'/play/',description,applicationCategory:'GameApplication',operatingSystem:'Web Browser',isAccessibleForFree:true}];if(slug&&!noindex)entities.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'CHEZZIES',item:origin+'/'},{'@type':'ListItem',position:2,name:h1,item:url}]});return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(intro)}"><meta name="theme-color" content="#0c2029"><meta name="robots" content="${noindex||(process.env.VERCEL_ENV==='preview')?'noindex,nofollow':'index,follow'}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:site_name" content="CHEZZIES"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(intro)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${origin}/marketing/world-wide.webp"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(intro)}"><meta name="twitter:image" content="${origin}/marketing/world-wide.webp"><link rel="icon" href="/favicon.svg">${game?'':'<link rel="stylesheet" href="/src/marketing.css">'}<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':entities}).replaceAll('<','\\u003c')}</script></head><body>${game?body:`<a class="skip" href="#main">Skip to content</a>${header}<main id="main">${body}</main>${footer}`}<script type="module" src="/src/${game?'international.tsx':'marketing.ts'}"></script></body></html>`;}
writeFileSync('index.html',html({title:'CHEZZIES — Chess Becomes an Adventure',h1:'Chess Becomes an Adventure',body:homepage(cta)}));
for(const p of pages){mkdirSync(p.slug,{recursive:true});const body=`<article class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">CHEZZIES</a><span>/</span><span>${p.slug.replaceAll('-',' ')}</span></nav><p class="eyebrow">THE CHEZZIES FIELD GUIDE</p><h1>${p.h1}</h1><p class="lead">${p.intro}</p>${cta()}<div class="article-body">${p.sections.map(([q,a],i)=>`<section id="${p.slug==='chess-puzzles-for-kids'?['checkmate','fork','pin','double-attack','defense','practice'][i]:'section-'+i}"><h2>${q}</h2><p>${a}</p></section>`).join('')}</div><aside class="related"><h2>Keep exploring</h2>${p.links.map(s=>`<a href="/${s}/">${pages.find(x=>x.slug===s).h1} ↗</a>`).join('')}${cta()}</aside></article>`;writeFileSync(p.slug+'/index.html',html({...p,body}));}
mkdirSync('play',{recursive:true});writeFileSync('play/index.html',html({title:'Play CHEZZIES — Your Free Chess Adventure',h1:'Play CHEZZIES',slug:'play',game:true,body:'<div id="root"><h1>Play CHEZZIES</h1><p>Your chess adventure is loading.</p></div><noscript>Enable JavaScript to play CHEZZIES. <a href="/how-to-play-chess-for-kids/">Read the beginner guide</a>.</noscript>'}));
writeFileSync('404.html',html({title:'Path not found | CHEZZIES',h1:'This path is still hidden',noindex:true,body:`<section class="not-found section"><p class="eyebrow">404 · A LITTLE DETOUR</p><h1>This path is still hidden.</h1><p>Let’s find your way back to the adventure.</p><a class="secondary" href="/">Return to the world ↗</a>${cta()}</section>`}));
const urls=['',...pages.map(p=>p.slug),'play'].map(s=>origin+'/'+(s?s+'/':''));
writeFileSync('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);
writeFileSync('public/robots.txt',(process.env.VERCEL_ENV==='preview')?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /play/account/\nDisallow: /play/login/\nSitemap: ${origin}/sitemap.xml\n`);
if(process.env.INDEXNOW_KEY){if(!/^[a-zA-Z0-9-]{8,128}$/.test(process.env.INDEXNOW_KEY))throw Error('Invalid IndexNow key');writeFileSync('public/'+process.env.INDEXNOW_KEY+'.txt',process.env.INDEXNOW_KEY);}

