import http from 'node:http';
import {readFileSync,existsSync,statSync} from 'node:fs';
import {resolve,extname,sep} from 'node:path';
const root=resolve('dist');const gameRoutes=new Set(['','home','login','account','reset-password','hero-select','profile','match','game','result']);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.mp4':'video/mp4','.xml':'application/xml','.txt':'text/plain'};
http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');let pathname;try{pathname=decodeURIComponent(u.pathname);}catch{res.writeHead(400);res.end();return;}
 if(pathname.startsWith('/api/')){if(!process.env.LOCAL_API_ORIGIN){res.writeHead(503,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Account service is not connected yet. Continue as a guest.'}));return;}try{const chunks=[];for await(const c of req)chunks.push(c);const r=await fetch(process.env.LOCAL_API_ORIGIN+u.pathname+u.search,{method:req.method,headers:{'Content-Type':'application/json',...(req.headers.cookie?{Cookie:req.headers.cookie}:{})},body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(chunks)});res.writeHead(r.status,{'Content-Type':'application/json',...(r.headers.getSetCookie().length?{'Set-Cookie':r.headers.getSetCookie()}:{})});res.end(Buffer.from(await r.arrayBuffer()));}catch{res.writeHead(502);res.end('{}');}return;}
 if(['/play/subscribe/','/play/payment/','/play/payment-success/','/play/billing-required/'].includes(pathname)){res.writeHead(307,{Location:'/play/home/'});res.end();return;}
 let relative=pathname;if(pathname.startsWith('/play/')&&gameRoutes.has(pathname.slice(6).replace(/\/$/,'')))relative='/play/index.html';let file=resolve(root,'.'+relative);if(file!==root&&!file.startsWith(root+sep)){res.writeHead(403);res.end();return;}if(existsSync(file)&&statSync(file).isDirectory())file=resolve(file,'index.html');let status=200;if(!existsSync(file)){file=resolve(root,'404.html');status=404;}res.writeHead(status,{'Content-Type':types[extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(readFileSync(file));}).listen(Number(process.env.PORT||4173),'127.0.0.1',()=>console.log('CHEZZIES preview at http://127.0.0.1:'+(process.env.PORT||4173)));
