import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {pieceNames,pieceSymbols} from '../../features/game/pieceLabels';
const pieces=Object.keys(pieceNames) as (keyof typeof pieceNames)[];
export default function MobilePieceGuide(){
 const [open,setOpen]=useState(false),[index,setIndex]=useState(0);
 const track=useRef<HTMLDivElement>(null),panel=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;panel.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const buttons=Array.from(panel.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')||[]);const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);trigger.current?.focus()};},[open]);
 function slide(i:number){setIndex(i);track.current?.scrollTo({left:i*track.current.clientWidth,behavior:window.matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}
 return <><button ref={trigger} className="mobile-piece-trigger lesson-secondary" onClick={()=>{setIndex(0);setOpen(true)}}>♟ Meet the pieces</button>{open&&createPortal(<div className="mobile-piece-layer" onClick={()=>setOpen(false)}><div ref={panel} className="mobile-piece-sheet" role="dialog" aria-modal="true" aria-label="Meet the pieces" onClick={e=>e.stopPropagation()}><header><strong>Meet the pieces</strong><button onClick={()=>setOpen(false)} aria-label="Close the piece guide">×</button></header><div className="mobile-piece-track" ref={track} onScroll={()=>{if(track.current)setIndex(Math.round(track.current.scrollLeft/track.current.clientWidth))}}>{pieces.map(type=><article key={type}><h2>{pieceNames[type]}</h2><div><img src={'/assets/pieces/w-'+type+'.png'} alt={"White "+pieceNames[type]}/><span>{pieceSymbols.w[type]}</span><img src={'/assets/pieces/b-'+type+'.png'} alt={"Black "+pieceNames[type]}/><span>{pieceSymbols.b[type]}</span></div></article>)}</div><footer><button aria-label="Previous piece" disabled={index===0} onClick={()=>slide(index-1)}>←</button><div>{pieces.map((p,i)=><button key={p} aria-label={pieceNames[p]} aria-current={i===index?'page':undefined} onClick={()=>slide(i)}>●</button>)}</div><button aria-label="Next piece" disabled={index===5} onClick={()=>slide(index+1)}>→</button></footer><p>Swipe through pieces · {index+1} / 6</p></div></div>,document.body)}</>;
}
